Remove old fun

diff --git a/bin/mkchroot b/bin/mkchroot
--- a/bin/mkchroot
+++ b/bin/mkchroot
@@ -1,19 +1,25 @@
-#!/bin/bash
+#!/bin/sh
 
 # Original version by Rob Landley of http://landley.net
 
-mkchroot() {
-  [ $# -lt 2 ] && return
+[ $# -lt 2 ] && { echo "usage: $0 <dest> targets ..."; exit 1; }
 
-  dest=$1
-  shift
+dest=$1
+shift
+
+[ ! -d "$dest" ] && { echo "error: dir '$dest' does not exists"; exit 1; }
+shift
+
+mkchroot() {
   for i in "$@"
   do
-    # Get an absolute path for the file
-    echo f: $i
-    [ "${i:0:1}" == "/" ] || i=$(which $i)
-    # Skip files that already exist at target.
-    [ -f "$dest/$i" ] && continue
+    echo $i | grep -qP '^\.?/' || i=$(which $i)
+
+    # Skip if target already exist
+    [ -e "$dest/$i" ] && continue
+
+    echo "f: $i -> $dest/$i"
+
     if [ -e "$i" ]
     then
       # Create destination path
@@ -25,7 +31,8 @@ mkchroot() {
     else
       echo "Not found: $i"
     fi
-    # Recursively copy shared libraries' shared libraries.
+
+    # Recursively copy shared libraries'
     mkchroot "$dest" $(ldd "$i" | egrep -o '/.* ')
   done
 }
